=== nip3o/tddd43/lab1/lab1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Definitions of attributes -->
    <xs:attribute name="id" type="xs:int"/>
    <xs:attribute name="expertAreaId" type="xs:int"/>
    <xs:attribute name="parentId" type="xs:int"/>
    
    <!-- Definitions of simple elements, quite nice to have them together in one place -->
    <xs:element name="name" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="justification" type="xs:string"/>
    
    <xs:element name="parentId" type="xs:int"/>
    <xs:element name="originatorId" type="xs:int"/>
    <xs:element name="expertId" type="xs:int"/>
    <xs:element name="expertAreaId" type="xs:int"/>
    <xs:element name="authorExpertId" type="xs:int"/>
    <xs:element name="recommendedExpertId" type="xs:int"/>
    
    <!-- Definitions of complex elements -->
    <xs:element name="expert">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="email"/>
                <xs:element name="expertises" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="expertise" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
        
        
        <xs:unique name="uniqueExpertId">
            <xs:selector xpath="experts/expert"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
    
    <xs:element name="expertArea">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element ref="originatorId"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
        
        <xs:unique name="uniqueExpertAreaId">
            <xs:selector xpath="expertAreas/expertArea"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
    
    <xs:element name="topicRelation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="expertAreaId"/>
                <xs:element ref="parentId"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="recommendation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="justification"/>
                <xs:element ref="authorExpertId"/>
                <xs:element ref="recommendedExpertId"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="expertise">
        <xs:complexType>
            <xs:attribute ref="expertAreaId" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Document definition, lab1 is the root element -->
    <xs:element name="lab1">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="experts">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="expert" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="expertAreas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="expertArea" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="topicRelations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="topicRelation" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="recommendations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="recommendation" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
        
        <xs:key name="expertAreaId">
            <xs:selector xpath=".//expertArea"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:keyref name="expertAreaIdConstraint" refer="expertAreaId">
            <xs:selector xpath=".//expertise"/>
            <xs:field xpath="@expertAreaId"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== nip3o/tddd43/lab1/lab1.xml
<?xml version="1.0" encoding="UTF-8"?>
<lab1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="lab1.xsd">
    <experts>
        <expert id="1">
            <name>Niclas Olofsson</name>
            <email>nicol271@student.liu.se</email>
        </expert>
        <expert id="2">
            <name>Holger Grenquist</name>
            <email>holger@grenquist.se</email>
        </expert>
    </experts>
    
    <expertAreas>
        <expertArea id="1">
            <description>Computer Science</description>
        </expertArea>
        <expertArea id="2" parentId="1">
            <description>Databases</description>
        </expertArea>
        <expertArea id="3" parentId="2">
            <description>SQL</description>
        </expertArea>
        <expertArea id="3" parentId="1">
            <description>Programming</description>
        </expertArea>
    </expertAreas>

    <expertises>
        <expertise>
            <expertId>1</expertId>
            <expertAreaId>45</expertAreaId>
        </expertise>
    </expertises>
    
    <recommendations>
        <recommendation>
            <justification>Has completed the TDDD43 LAB 1</justification>
            <authorExpertId>1</authorExpertId>
            <recommendedExpertId>2</recommendedExpertId>
        </recommendation>
    </recommendations>
    
    
</lab1>
